{
 "title": "AIOps health overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Policy engine uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{pod=~\"aiops-ir-lifecycle-eventprocessor-ep-jobmanager-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data layer uptime",
   "type": "stat",
   "description": "Uptime of the data layer instances, which are responsible for persisting updates to alerts and incidents",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready_time{pod=~\"aiops-ir-core-ncodl-std-.*\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Events ingested in time range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.events\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "state-timeline",
   "description": "Status of the policy engine over time",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_uptime{pod=~\"aiops-ir-lifecycle-eventprocessor-ep-jobmanager-.*\"} > 600000)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "state-timeline",
   "description": "Status of the datalayer over time",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{deployment=\"aiops-ir-core-ncodl-std\"} / kube_deployment_status_replicas{deployment=\"aiops-ir-core-ncodl-std\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Dropped alert/incident updates",
   "type": "stat",
   "description": "Count of incident and alert updates which were dropped by the data layer in the current time period",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.errors\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Event processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Event rates",
   "type": "timeseries",
   "description": "Shows the rates of events ingested into the system, as well as the processing rates by the policy engine. These should roughly match if the system is healthy.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.events\"}[1m]))",
     "legendFormat": "Incoming events"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4aiops_cartridge_lifecycle_input_events\"}>0)[1m:30s]))",
     "legendFormat": "Input to policy engine"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"updated_events_output:_Writer\"}>0)[1m:30s]))",
     "legendFormat": "Processed by policy engine"
    }
   ]
  },
  {
   "title": "Alert request rates",
   "type": "timeseries",
   "description": "Shows the rate of alert requests being fed into the policy system and persistence layers. Note that this includes both inserts and updates, so will exceed the number of created alerts.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.alerts\"}[1m]))",
     "legendFormat": "Alert requests to policy engine"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.alerts\"}[1m]))",
     "legendFormat": "Alert requests to persistence"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.changes.alerts\"}[1m]))",
     "legendFormat": "Persisted changes to alerts"
    }
   ]
  },
  {
   "title": "Incident request rates",
   "type": "timeseries",
   "description": "Shows the rate of incident requests being fed into the policy system and persistence layers. Note that this includes both inserts and updates, so will exceed the number of created incidents.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.stories\"}[1m]))",
     "legendFormat": "Incident requests to policy engine"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.stories\"}[1m]))",
     "legendFormat": "Incident requests to persistence"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.changes.stories\"}[1m]))",
     "legendFormat": "Persisted changes to incidents"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "description": "Shows the rate of incident requests being fed into the policy system and persistence layers. Note that this includes both inserts and updates, so will exceed the number of created incidents.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyFailures)",
     "legendFormat": "Policy failures"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyTimeouts)",
     "legendFormat": "Policy timeouts"
    },
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.errors\"}[1m]))",
     "legendFormat": "Persistence errors"
    }
   ]
  },
  {
   "title": "Average message size",
   "type": "timeseries",
   "description": "The average size of kafka messages, as measured at the broker. This will effect I/O pressure and storage.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.events\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.events\"}[1m]) ) by (topic)",
     "legendFormat": "Events"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.alerts\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.alerts\"}[1m]) ) by (topic)",
     "legendFormat": "Alert requests (to policy engine)"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.alerts\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.alerts\"}[1m]) ) by (topic)",
     "legendFormat": "Alert requests (to persistence)"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.stories\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.input.stories\"}[1m]) ) by (topic)",
     "legendFormat": "Story requests (to policy engine)"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.stories\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.irdatalayer.requests.stories\"}[1m]) ) by (topic)",
     "legendFormat": "Story requests (to persistence)"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"cp4aiops-cartridge.lifecycle.internal.in-progress-executions\"}[1m]) / irate(kafka_server_brokertopicmetrics_messagesin_total{topic=\"cp4aiops-cartridge.lifecycle.internal.in-progress-executions\"}[1m]) ) by (topic)",
     "legendFormat": "Intermediate policy results"
    }
   ]
  },
  { "title": "Policy execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Scheduler requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerCompletions)",
     "legendFormat": "Completions"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerRequests)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Checkpoint durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration",
     "legendFormat": "Checkpoint duration"
    },
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize",
     "legendFormat": "Checkpoint size"
    }
   ]
  },
  {
   "title": "Policy engine CPU usage (average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) / (sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) + sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m]))))",
     "legendFormat": "{{ pod }} thottling"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])))",
     "legendFormat": "{{ pod }} usage"
    }
   ]
  },
  {
   "title": "Policy engine CPU usage (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) / (sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) + sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m]))))",
     "legendFormat": "{{ pod }} thottling"
    },
    {
     "expr": "max(sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])))",
     "legendFormat": "{{ pod }} usage"
    }
   ]
  }
 ]
}