{
 "title": "AIOps lifecycle monitoring",
 "time": { "from": "2024-06-11T13:49:37.129Z", "to": "2024-06-11T14:52:16.558Z" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Connectors & inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connector bridge messages received",
     "type": "graph",
     "description": "Rate of messages received by connector bridge ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(grpc_server_msg_received_total{namespace=\"cp4waiops\"}[1m])",
       "legendFormat": "{{ grpc_method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_jobmanager_job_uptime)",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Restart rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_numRestarts[1m])"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (max_over_time(flink_taskmanager_job_task_operator_pendingRecords[5m]) >= 0)",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (deriv(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max[1m]) == deriv(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max[1m]))",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Estimated kafka input rate",
   "type": "timeseries",
   "description": "Total rate of messages published to kafka, including those not being consumed due to backpressure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (task_name) (irate((flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_total + flink_taskmanager_job_task_operator_pendingRecords)[5m:5m]))",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag (by subtask)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (task_name, subtask_index) (flink_taskmanager_job_task_operator_pendingRecords)",
     "legendFormat": "{{task_name}} ({{subtask_index}})"
    }
   ]
  },
  { "title": "Watermarks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Watermark alignment drift (alerts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_watermarkAlignmentDrift{task_name=\"Source:_source:events_input____events_input::mapper____Filter\"} > -10000000",
     "legendFormat": "Events ({{subtask_index}})"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_watermarkAlignmentDrift{task_name=\"Source:_source:alerts_input____alerts_input::deserialize\"} > -10000000",
     "legendFormat": "Alerts input ({{subtask_index}})"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_watermarkAlignmentDrift{task_name=\"Source:_source:alerts_changes____alerts_changes::deserialize\"} > -10000000",
     "legendFormat": "Alerts changes ({{subtask_index}})"
    }
   ]
  },
  {
   "title": "Watermark lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (task_name) (flink_taskmanager_job_task_operator_watermarkLag)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Events vs Alert input vs changes watermarks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "max by (task_name, subtask_index) (flink_taskmanager_job_task_operator_currentOutputWatermark{task_name=\"Source:_source:events_input____events_input::mapper____Filter\"} > 0)",
     "legendFormat": "Events ({{subtask_index}})"
    },
    {
     "expr": "max by (task_name, subtask_index) (flink_taskmanager_job_task_operator_currentOutputWatermark{task_name=\"Source:_source:alerts_input____alerts_input::deserialize\"} > 0)",
     "legendFormat": "Alerts input ({{subtask_index}})"
    },
    {
     "expr": "max by (task_name, subtask_index) (flink_taskmanager_job_task_operator_currentOutputWatermark{task_name=\"Source:_source:alerts_changes____alerts_changes::deserialize\"} > 0)",
     "legendFormat": "Alerts changes ({{subtask_index}})"
    }
   ]
  },
  {
   "title": "Source idle time (alerts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_sourceIdleTime{task_name=\"Source:_source:alerts_input____alerts_input::deserialize\"} > -10000000",
     "legendFormat": "Alerts input ({{subtask_index}})"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_sourceIdleTime{task_name=\"Source:_source:alerts_changes____alerts_changes::deserialize\"} > -10000000",
     "legendFormat": "Alerts changes ({{subtask_index}})"
    }
   ]
  },
  {
   "title": "Source idle time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (task_name) (flink_taskmanager_job_task_operator_sourceIdleTime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operator bytes in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_numBytesInPerSecond)",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Operator bytes out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_numBytesOutPerSecond)",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Broadcast operator output req per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond{task_name=\"policy_exec::broadcast_refresh_policies\"})",
     "legendFormat": "Subtask {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Operator load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alert input backpressured time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=\"alerts_input::merge_requests____alerts_input::create_execution_request\"}/10",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Alert changes backpressured time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=\"alerts_changes::merge_notifications____alerts_changes::create_execution_request\"}/10",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Requests source busy time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=\"execution_requests:set_global_variables\"}/10)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Requests source backpressured time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=\"execution_requests:set_global_variables\"}/10",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Policy execution results source backpressured time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=\"Source:_source:policy_execution_results____policy_execution_results::deserialize\"}/10)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Scheduler backpressured time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=\"policy_exec::schedule_policy_execution\"}/10",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Scheduler busy time",
   "type": "timeseries",
   "description": "Percentage of time the synchronous policy executor was busy in each time period. 100% means it is executing as fast as it can and is saturated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=\"policy_exec::schedule_policy_execution\"}/10)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Sync executor backpressured time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_backPressuredTimeMsPerSecond{task_name=~\"policy_exec::execute_sync_policy_stages.*\"}/10",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Sync policy executor busy time",
   "type": "graph",
   "description": "Percentage of time the synchronous policy executor was busy in each time period. 100% means it is executing as fast as it can and is saturated.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"policy_exec::execute_sync_policy_stages.*\"}/10)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Kafka async policy executor busy time",
   "type": "graph",
   "description": "Percentage of time the synchronous policy executor was busy in each time period. 100% means it is executing as fast as it can and is saturated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_busyTimeMsPerSecond{task_name=~\"policy_exec::execute_kafka_async_policy_stages.*\"}/10)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Checkpointing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Checkpoint alignment (0 subtasks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{subtask_index=\"0\"}",
     "legendFormat": "{{ task_name }}-{{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Checkpoint alignment (1 subtasks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{subtask_index=\"1\"}",
     "legendFormat": "{{ task_name }}-{{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Checkpoint alignment (2 subtasks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{subtask_index=\"2\"}",
     "legendFormat": "{{ task_name }}-{{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Checkpoint alignment (3 subtasks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{subtask_index=\"3\"}",
     "legendFormat": "{{ task_name }}-{{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Checkpoint durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration",
     "legendFormat": "Checkpoint duration"
    },
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize",
     "legendFormat": "Checkpoint size"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "targets": [
    {
     "expr": "rate(flink_jobmanager_job_numberOfCompletedCheckpoints[1m:30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerCompletions)",
     "legendFormat": "Completions"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerRequests)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Scheduler requests by subtask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerRequests) by (subtask_index)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Queue age",
   "type": "timeseries",
   "description": "An estimate of the age of the oldest item in the queue. Gives a measure of how long items are queued for.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_operator_partitionKey_schedulerPartitionQueuedRequests) / sum by (subtask_index) (flink_taskmanager_job_task_operator_schedulerCompletions)",
     "legendFormat": "Index {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Policy executor incoming requests by subtask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{task_name=~\"policy_exec::execute_sync_policy_stages.*\"}) by (subtask_index)",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Request queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_operator_partitionKey_schedulerPartitionQueuedRequests)",
     "legendFormat": "Index {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Request queue size by partition (top 10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk (10, flink_taskmanager_job_task_operator_partitionKey_schedulerPartitionQueuedRequests)",
     "legendFormat": "{{ partitionKey }}"
    }
   ]
  },
  {
   "title": "In flight requests counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (subtask_index) (flink_taskmanager_job_task_operator_schedulerQueuedRequests)",
     "legendFormat": "Index {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Request queue distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "sum by (subtask_index, partitionKey) (avg_over_time(flink_taskmanager_job_task_operator_partitionKey_schedulerPartitionQueuedRequests[$__range]))",
     "legendFormat": "{{ subtask_index }}-{{ partitionKey }}"
    }
   ]
  },
  {
   "title": "Request to policy request ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyRequests) / sum(flink_taskmanager_job_task_operator_schedulerRequests)",
     "legendFormat": "PolicyExecutionRequests per ExecutionRequest"
    }
   ]
  },
  {
   "title": "Scheduler policy requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyRequests)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyFailures)",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions)",
     "legendFormat": "Completions"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyTimeouts)",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "Scheduler policy request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_policyId_schedulerPolicyTotalTimeSpent) / sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions)",
     "legendFormat": "Total latency"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_policyId_schedulerPolicyCpuTimeSpent) / sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Request completions to policy result ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions + flink_taskmanager_job_task_operator_schedulerPolicyFailures) / sum(flink_taskmanager_job_task_operator_schedulerCompletions)",
     "legendFormat": "PolicyResults per ExecutionRequest"
    }
   ]
  },
  {
   "title": "Scheduler request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_policyId_schedulerPolicyTotalTimeSpent) * (sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions + flink_taskmanager_job_task_operator_schedulerPolicyFailures) / sum(flink_taskmanager_job_task_operator_schedulerCompletions)) / sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions)",
     "legendFormat": "Total latency"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_policyId_schedulerPolicyCpuTimeSpent)  * (sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions + flink_taskmanager_job_task_operator_schedulerPolicyFailures) / sum(flink_taskmanager_job_task_operator_schedulerCompletions)) / sum(flink_taskmanager_job_task_operator_schedulerPolicyCompletions)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ODF Storage latancy",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "odf_system_latency_seconds" }
     ]
    },
    {
     "title": "PV Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes * 100)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dependencies (Kafka/Cassandra)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Kafka CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=\"kafka\"}[1m])",
       "legendFormat": "{{ pod }} thottling"
      },
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"kafka\"}[1m])",
       "legendFormat": "{{ pod }} usage"
      }
     ]
    },
    {
     "title": "Cassandra CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=\"aiops-topology-cassandra\"}[1m])",
       "legendFormat": "{{ pod }} thottling"
      },
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"aiops-topology-cassandra\"}[1m])",
       "legendFormat": "{{ pod }} usage"
      }
     ]
    },
    {
     "title": "Kafka network receve rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"iaf-system-kafka-[0-9]+\"}[4h:30s])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Cassandra network receive rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"aiops-topology-cassandra-[0-9]+\"}[4h:30s])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Kafka network transmit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"iaf-system-kafka-[0-9]+\"}[4h:30s])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Cassandra network transmit rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"aiops-topology-cassandra-[0-9]+\"}[4h:30s])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Topology Status Service CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=\"aiops-topology-status\"}[1m])",
       "legendFormat": "{{ pod }} thottling"
      },
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"aiops-topology-status\"}[1m])",
       "legendFormat": "{{ pod }} usage"
      }
     ]
    },
    {
     "title": "Datalayer standard Service CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"standard\"}[1m]))",
       "legendFormat": "{{ pod }} thottling"
      },
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"standard\"}[1m]))",
       "legendFormat": "{{ pod }} usage"
      }
     ]
    },
    {
     "title": "Postgres CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"postgres\"}[1m]))",
       "legendFormat": "{{ pod }} thottling"
      },
      {
       "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"postgres\"}[1m]))",
       "legendFormat": "{{ pod }} usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Used"
    },
    {
     "expr": "sum by (pod, tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Max{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Total"
    }
   ]
  },
  {
   "title": "Memory (heap vs container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Heap used"
    },
    {
     "expr": "sum by (pod, tm_id) (flink_taskmanager_Status_JVM_Memory_Heap_Max{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Heap max"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"aiops-ir-lifecycle-eventprocessor-ep-taskmanager-[0-9]+\", container=\"taskmanager\"}",
     "legendFormat": "{{pod}} container used"
    }
   ]
  },
  {
   "title": "Classes loaded / unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (flink_taskmanager_Status_JVM_ClassLoader_ClassesLoaded{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Loaded"
    },
    {
     "expr": "- sum by (pod) (flink_taskmanager_Status_JVM_ClassLoader_ClassesUnloaded{pod=~\"aiops-ir-.*\"})",
     "legendFormat": "{{ pod }} Unloaded"
    }
   ]
  },
  {
   "title": "Flink task manager CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) / (sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) + sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])))",
     "legendFormat": "{{ pod }} thottling"
    },
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m]))",
     "legendFormat": "{{ pod }} usage"
    }
   ]
  },
  {
   "title": "Memory (policy sync task)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_usage_bytes{container=\"ibm-lifecycle-policy-sync\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Flink task manager CPU usage (average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) / (sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])) + sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m]))))",
     "legendFormat": "{{ pod }} thottling"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{container=\"taskmanager\", pod=~\"aiops-ir-lifecycle.*\"}[1m])))",
     "legendFormat": "{{ pod }} usage"
    }
   ]
  },
  {
   "title": "GC time spent (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(flink_taskmanager_Status_JVM_GarbageCollector_global_Time{pod=~\"aiops-ir-.*\"}[1m]) / 1000)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(flink_taskmanager_Status_JVM_GarbageCollector_global_Count{pod=~\"aiops-ir-.*\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Message I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Events in vs alerts/stories out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_events\"}>0)[1m:30s]))",
     "legendFormat": "Events input"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"alerts_input:_Writer\"}>0)[1m:30s]))",
     "legendFormat": "Alerts input"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"alerts_output:_Writer\"}>0)[1m:30s]))",
     "legendFormat": "Alerts output"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"stories_output:_Writer\"}>0)[1m:30s]))",
     "legendFormat": "Stories output"
    }
   ]
  },
  {
   "title": "I/O summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_events\"}>0)[1m:30s]))",
     "legendFormat": "Events input"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_alerts_output\"}>0)[1m:30s]))",
     "legendFormat": "Alerts output"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_stories_output\"}>0)[1m:30s]))",
     "legendFormat": "Stories output"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_alerts\"}>0)[1m:30s]))",
     "legendFormat": "Alerts input"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_stories\"}>0)[1m:30s]))",
     "legendFormat": "Stories input"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_stories\"}>0)[1m:30s]))",
     "legendFormat": "Stories changes"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_alerts\"}>0)[1m:30s]))",
     "legendFormat": "Alerts changes"
    },
    {
     "expr": "sum(irate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_internal_in_progress_executions\"}>0)[1m:30s]))",
     "legendFormat": "Execution results"
    }
   ]
  },
  {
   "title": "Topology requests vs responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_output_topology_alert_response\"}>0)[1m:30s]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "sum(rate((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_topology_requests\"}>0)[1m:30s]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "I/O summary (Total count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_events\"}>0))",
     "legendFormat": "Events input"
    },
    {
     "expr": "sum((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_alerts_output\"}>0))",
     "legendFormat": "Alerts output"
    },
    {
     "expr": "sum((flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_stories_output\"}>0))",
     "legendFormat": "Stories output"
    },
    {
     "expr": "sum(((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_alerts\"}>0)))",
     "legendFormat": "Alerts input"
    },
    {
     "expr": "sum(((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_stories\"}>0)))",
     "legendFormat": "Stories input"
    },
    {
     "expr": "sum(((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_stories\"}>0)))",
     "legendFormat": "Stories changes"
    },
    {
     "expr": "sum(((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_alerts\"}>0)))",
     "legendFormat": "Alerts changes"
    },
    {
     "expr": "sum(((flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_internal_in_progress_executions\"}>0)))",
     "legendFormat": "Execution results"
    }
   ]
  },
  {
   "title": "Event input topic partition balence",
   "type": "graph",
   "description": "Highlights data skew in the event input topic. A heavily loaded partition indicates that an event source is not setting the event key correctly.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (irate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_events\"}[4h:30s]))",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "I/O summary (10m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_events\"}[10m]))",
     "legendFormat": "Events input"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_alerts_output\"}[10m]))",
     "legendFormat": "Alerts output"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{operator_name=\"Sink:_stories_output\"}[10m]))",
     "legendFormat": "Stories output"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_alerts\"}[10m]))",
     "legendFormat": "Alerts input"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_stories\"}[10m]))",
     "legendFormat": "Stories input"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_stories\"}[10m]))",
     "legendFormat": "Stories changes"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_alerts\"}[10m]))",
     "legendFormat": "Alerts changes"
    },
    {
     "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_internal_in_progress_executions\"}[10m]))",
     "legendFormat": "Execution results"
    }
   ]
  },
  {
   "title": "Kafka producer batch size (avg)",
   "type": "timeseries",
   "description": "Average size of each message batch",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 267 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(operator_name) (flink_taskmanager_job_task_operator_KafkaProducer_batch_size_avg > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Summary (data)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 267 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (task_name) (flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate)",
     "legendFormat": "{{ task_name }}"
    }
   ]
  },
  {
   "title": "Outgoing producer request latency (avg)",
   "type": "timeseries",
   "description": "Average time between a message being emitted and it being sent. This will be affected by the linger time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 275 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka producer batch size (max)",
   "type": "timeseries",
   "description": "Max size of each message batch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 275 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(operator_name) (flink_taskmanager_job_task_operator_KafkaProducer_batch_size_max > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing producer byte rate",
   "type": "timeseries",
   "description": "Outgoing data rate ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing producer request latency (max)",
   "type": "timeseries",
   "description": "Maximum time between a message being emitted and it being sent. This will be affected by the linger time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 283 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_KafkaProducer_request_latency_max > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing producer message rate",
   "type": "timeseries",
   "description": "Outgoing rate of message sends",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 291 },
   "fieldConfig": { "defaults": { "unit": "wpm" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_record_send_rate) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing producer compression ratio",
   "type": "timeseries",
   "description": "Ratio of uncompressed vs compressed batch size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 291 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(1 / flink_taskmanager_job_task_operator_KafkaProducer_compression_rate_avg > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average message size",
   "type": "timeseries",
   "description": "Average size of each message",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_record_size_avg > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request size",
   "type": "timeseries",
   "description": "Average size of each request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 299 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaProducer_request_size_avg > 0) by (operator_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert input topic partition balence",
   "type": "graph",
   "description": "Highlights data skew in the alert input topic. A heavily loaded partition indicates that an event source is not setting the event key correctly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 307 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (irate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_lifecycle_input_alerts\"}[4h:30s]))",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "Alert changes topic partition balence",
   "type": "graph",
   "description": "Highlights data skew in the alert input topic. A heavily loaded partition indicates that an event source is not setting the event key correctly.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 315 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (partition) (irate(flink_taskmanager_job_task_operator_KafkaSourceReader_topic_partition_currentOffset{topic=\"cp4waiops_cartridge_irdatalayer_changes_alerts\"}[4h:30s]))",
     "legendFormat": "{{ partition }}"
    }
   ]
  },
  {
   "title": "Action execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 323 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Action execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 324 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile) (flink_taskmanager_job_task_operator_actionExecutionTime)",
     "legendFormat": "{{ quantile }} percentile"
    }
   ]
  },
  {
   "title": "Action execution rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 324 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (subtask_index) (rate(flink_taskmanager_job_task_operator_actionExecutionTime_count[1m]))",
     "legendFormat": "Subtask {{ subtask_index }}"
    }
   ]
  },
  {
   "title": "Policy CPU usage by policy (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 332 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (policyId) (irate(flink_taskmanager_job_task_operator_policyId_schedulerPolicyCpuTimeSpent[1m]))/1000",
     "legendFormat": "{{ policyId }}"
    }
   ]
  },
  {
   "title": "Policy round trip time per second by policy (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 340 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (policyId) (irate(flink_taskmanager_job_task_operator_policyId_schedulerPolicyTotalTimeSpent[1m]))/1000",
     "legendFormat": "{{ policyId }}"
    }
   ]
  }
 ]
}